### ISSUE TITLE
Problem compiling portaudio on macOS

### ISSUE THREAD

**Issue by draeron** [LedFx/ledfx_v3#94]
**Describe the bug**

When trying to build ledfx on a MBA m2 on monterey I get this error. 

```
github.com/LedFx/portaudio
# github.com/LedFx/portaudio
../../../go/pkg/mod/github.com/!led!fx/portaudio@v0.0.0-20220904153216-3555838c5db4/portaudio.go:200:32: could not determine kind of name for C.paPulseAudio
```

**LedFx Host Information (please complete the following information):**
 - OS: macos 12.6 Monterey 
 - GO version: go1.19.2 darwin/arm64
 - PulseAudio (homebrew): pulseaudio 14.2
 - LedFx Version: commit:0c52f7cb7ffdb4db62322d9b8cf531e65532ba6c

**Additional context**
I'm probably the first trying this on a mac. Was curious about performance.

**Comment by draeron** [comment]
unstale

**Comment by draeron** [comment]
unstale

**Comment by draeron** [comment]
unstale

**Comment by spiro-c** [comment]
to build it you need to revert the portaudio from `github.com/LedFx/portaudio` to `github.com/gordonklaus/portaudio` and again i think it's not in usable state ...
