### ISSUE TITLE
Add contribution page 

### ISSUE THREAD

**Issue by rvatok** [LedFx/ledfx_v3#95]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Traceback**
If applicable, add the traceback log that LedFx outputs when it encounters an error.
Usually starts with "Traceback (most recent call last):"

**LedFx Host Information (please complete the following information):**
 - OS: [e.g. Windows 11]
 - LedFx Version:  [e.g. 0.8.9 - use ledfx --version to find out]

**Additional context**

**Comment by bigredfrog** [comment]
We really should have one, assuming this comment keeps issue open
